server:
  port: 8082

spring:
  application:
    name: order-service
  cloud:
    openfeign:
      micrometer:
        enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
    brave:
      span-joining-supported: true
    baggage:
      enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
